const init = [
	`CREATE TABLE IF NOT EXISTS auth (id VARCHAR(32) NOT NULL ,name VARCHAR(255) NOT NULL,password VARCHAR(255) NOT NULL,role VARCHAR(6) NOT NULL,PRIMARY KEY (id));`,
	`CREATE TABLE IF NOT EXISTS user (id VARCHAR(32) NOT NULL ,rides INT(3),PRIMARY KEY (id));`,
	`CREATE TABLE IF NOT EXISTS driver (id VARCHAR(32) NOT NULL ,rides INT(3),PRIMARY KEY (id));`,
	`CREATE TABLE IF NOT EXISTS car (id VARCHAR(32) NOT NULL ,driverId VARCHAR(32) NOT NULL,PRIMARY KEY (id));`,
	`CREATE TABLE IF NOT EXISTS ride (id VARCHAR(32) NOT NULL ,driverId VARCHAR(32),userId VARCHAR(32) NOT NULL,status VARCHAR(16),PRIMARY KEY (id));`,
];
module.exports = init;
