const init = [
	`CREATE TABLE IF NOT EXISTS auth (uid VARCHAR(32) NOT NULL ,name VARCHAR(255) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,role VARCHAR(6) NOT NULL,PRIMARY KEY (uid));`,
	`CREATE TABLE IF NOT EXISTS user (uid VARCHAR(32) NOT NULL ,full_name VARCHAR(255),rides INT(3),PRIMARY KEY (uid),FOREIGN KEY (uid) REFERENCES auth(uid));`,
	`CREATE TABLE IF NOT EXISTS driver (uid VARCHAR(32) NOT NULL ,full_name VARCHAR(255),address VARCHAR(255),rides INT(3),PRIMARY KEY (uid),FOREIGN KEY (uid) REFERENCES auth(uid));`,
	`CREATE TABLE IF NOT EXISTS car (cid VARCHAR(32) NOT NULL ,driverId VARCHAR(32) NOT NULL,reg_no VARCHAR(32),PRIMARY KEY (cid),FOREIGN KEY (driverId) REFERENCES driver(uid));`,
	`CREATE TABLE IF NOT EXISTS ride (rid VARCHAR(32) NOT NULL ,driverId VARCHAR(32),userId VARCHAR(32) NOT NULL,status VARCHAR(16),time VARCHAR(10),source VARCHAR(255), destination VARCHAR(255),PRIMARY KEY (rid),FOREIGN KEY (driverId) REFERENCES driver(uid),FOREIGN KEY (userId) REFERENCES user(uid));`,
];

module.exports = init;
